### ISSUE TITLE
Cannot use this action in a chain

### ISSUE THREAD

**Issue by LecrisUT** [re-actors/alls-green#25] opened 2023-12-04 15:05 UTC
Example:
```yaml
  test:
    uses: ...
    if: "! inputs.skip-tests"

  test-status:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: test
          jobs: ${{ toJSON(needs) }}
    if: always()

  build:
    needs: [ test-status ]
    uses: ...
```

The latter job is not run, probably because of the `needs` of the former

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/re-actors) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/re-actors/alls-green/issues/25">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/re-actors/alls-green/issues/25/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/re-actors/alls-green/issues/25/pledge.svg">
</picture>
</a>

**Comment by webknjaz** [comment] 2023-12-04 17:02
That works in our own CI. Perhaps, yours is misconfigured somehow 🤷‍♂️.

Anyway, it's not something related to the action (as it only works with the inputs passed in), but is happening on the workflow definition level, which we wouldn't be able to control, even if we wanted to.

Closing as it's not a bug for us, but something on the calling side.

**Closed** 2023-12-04 17:02 UTC

**Comment by webknjaz** [comment] 2023-12-04 17:10
If you want to run a job despite test-status failing, you'll have to stick `if: always()` there too. Although I don't know what use case this would actually support.

**Comment by LecrisUT** [comment] 2023-12-04 21:06
I should clarify the example given. The issue is when `test` job is skipped, `test-status` of course runs, but `build` is skipped as if the skip status propagated through. I'll make a mwe tomorrow.

Indeed this is a usage issue, but it is not intuitive how it should be configured, so some documentation would be helpful for such scenario.

**Comment by LecrisUT** [comment] 2023-12-05 10:02
@webknjaz here is a mwe if you have any pointers about it: https://github.com/LecrisUT/all-greens-example
